# bit.ly/2lsQni7 ( 소문자 L )
파일 -> .ipynb 다운로드 -> 실습폴더에 업로드 하여 사용

# 모의고사2

# Q1.  ex2 파일을 참고하여, boston데이터에서 x와 y를 선언하라

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston

In [2]:
boston = load_boston()

In [3]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [4]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [5]:
type(x), type(y)

(numpy.ndarray, numpy.ndarray)

In [6]:
y = y.reshape( [ -1 , 1])

In [7]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [8]:
data = pd.DataFrame(data = x,
                   columns = boston.feature_names)

data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [9]:
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

# Q2. 전처리를 하자!

1. Target은 그대로 둘 것.
2. Description을 보고..
    1. 카테고리여야 할 것 같은 것은 더미!
    2. 그렇지 않은 것은 Min-Max Scailing


In [10]:
data_origin = data.copy()

In [11]:
a = np.array( [1,2,3,4,5]   )
b = a[:3]

a, b

(array([1, 2, 3, 4, 5]), array([1, 2, 3]))

In [12]:
b[1] = 10

In [13]:
b

array([ 1, 10,  3])

In [14]:
a

array([ 1, 10,  3,  4,  5])

In [15]:
data.head(4)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94

In [16]:
cols = list(data)

In [17]:
cols.remove(    'CHAS')
# try except, catch

In [18]:
for each in cols :
    min_each = data[each].min()
    max_each = data[each].max()
    boonmo = max_each - min_each
    data[each] = (data[each]-min_each)/boonmo
    
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     0.040544    0.113636    0.391378    0.069170    0.349167    0.521869   
std      0.096679    0.233225    0.251479    0.253994    0.238431    0.134627   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000851    0.000000    0.173387    0.000000    0.131687    0.445392   
50%      0.002812    0.000000    0.338343    0.000000    0.314815    0.507281   
75%      0.041258    0.125000    0.646628    0.000000    0.491770    0.586798   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     0.676364    0.242381    0.371713    0.422208    0.622929    0.898568   
std      0.289896    0.191482    0.378576    0.321636    0.230313    0.230205   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.433831    0.088259    0.130435    0.175573    0.510638    0.945730   
50%      0.768280    0.188949    0.173913    0.272901    0.686170    0.986232   
75%      0.938980    0.369088    1.000000    0.914122    0.808511    0.998298   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

            LSTAT  
count  506.000000  
mean     0.301409  
std      0.197049  
min      0.000000  
25%      0.144040  
50%      0.265728  
75%      0.420116  
max      1.000000

In [19]:
#x = data_origin.values
x = data.values

In [20]:
x.shape, y.shape

((506, 13), (506, 1))

In [21]:
type(x), type(y)

(numpy.ndarray, numpy.ndarray)

# Q3. 모델링을 하자!

* Linear Regression을 한다!

* KNN을 이용한 Regression 도 해본다!

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

In [24]:
lr = LinearRegression()
kr = KNeighborsRegressor()

In [25]:
lr.fit(x, y)
kr.fit(x, y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [26]:
l_pred = lr.predict(x)
k_pred = kr.predict(x)

# Q4. 평가하자!
* MSE 혹은 RMSE를 구해보자!
* R^2 값을 구해보자! ( Scikit-learn 의 r2_score 참고!)

### 쉬운길

In [27]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [28]:
print("선형회귀의 rmse : {:.3f}".format(np.sqrt(mean_squared_error(y, l_pred))))
print("KNN회귀의 rmse : {:.3f}".format(np.sqrt(mean_squared_error(y, k_pred))))

선형회귀의 rmse : 4.679
KNN회귀의 rmse : 3.551


In [29]:
print("선형회귀의 rmse : {:.3f}".format(r2_score(y, l_pred)))
print("KNN회귀의 rmse : {:.3f}".format(r2_score(y, k_pred)))

선형회귀의 rmse : 0.741
KNN회귀의 rmse : 0.851


In [30]:
data_origin.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [31]:
data_origin.head(5)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [32]:
lr.coef_

array([[ -9.60975755,   4.64204584,   0.56083933,   2.68673382,
         -8.63457306,  19.88368651,   0.06721501, -16.22666104,
          7.03913802,  -6.46332721,  -8.95582398,   3.69282735,
        -19.01724361]])

In [33]:
lr.intercept_

array([26.62026758])

In [34]:
data['target'] = y
data.head()

CRIM    ZN     INDUS  CHAS       NOX        RM       AGE       DIS  \
0  0.000000  0.18  0.067815   0.0  0.314815  0.577505  0.641607  0.269203   
1  0.000236  0.00  0.242302   0.0  0.172840  0.547998  0.782698  0.348962   
2  0.000236  0.00  0.242302   0.0  0.172840  0.694386  0.599382  0.348962   
3  0.000293  0.00  0.063050   0.0  0.150206  0.658555  0.441813  0.448545   
4  0.000705  0.00  0.063050   0.0  0.150206  0.687105  0.528321  0.448545   

        RAD       TAX   PTRATIO         B     LSTAT  target  
0  0.000000  0.208015  0.287234  1.000000  0.089680    24.0  
1  0.043478  0.104962  0.553191  1.000000  0.204470    21.6  
2  0.043478  0.104962  0.553191  0.989737  0.063466    34.7  
3  0.086957  0.066794  0.648936  0.994276  0.033389    33.4  
4  0.086957  0.066794  0.648936  1.000000  0.099338    36.2

In [35]:
data_origin['target'] = y

In [36]:
data_origin.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [37]:
# 
kr.kneighbors( x[0:1])


(array([[0.        , 0.32407626, 0.33999584, 0.36502483, 0.37392712]]),
 array([[  0, 177, 178,  89,  90]], dtype=int64))

In [38]:
kr.kneighbors( x[0:1])[1][0].tolist()

[0, 177, 178, 89, 90]

In [39]:
data_origin.iloc[kr.kneighbors( x[0:1])[1][0].tolist()]

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
177  0.05425   0.0   4.05   0.0  0.510  6.315  73.4  3.3175  5.0  296.0   
178  0.06642   0.0   4.05   0.0  0.510  6.860  74.4  2.9153  5.0  296.0   
89   0.05302   0.0   3.41   0.0  0.489  7.079  63.1  3.4145  2.0  270.0   
90   0.04684   0.0   3.41   0.0  0.489  6.417  66.1  3.0923  2.0  270.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
177     16.6  395.60   6.29    24.6  
178     16.6  391.27   6.92    29.9  
89      17.8  396.06   5.70    28.7  
90      17.8  392.18   8.81    22.6

In [40]:
import random as rd
idx = rd.randint(0, 100)
print("{}번 row와 가장 가까운 것을 보고 싶다!".format(idx))
input_ = x[idx].reshape([1,-1])
print(kr.kneighbors(input_))

data.iloc[kr.kneighbors( input_ )[1][0].tolist()    ]

35번 row와 가장 가까운 것을 보고 싶다!
(array([[0.        , 0.09937221, 0.17167551, 0.21871557, 0.22131419]]), array([[ 35,  36, 323,  87, 318]], dtype=int64))


CRIM   ZN     INDUS  CHAS       NOX        RM       AGE       DIS  \
35   0.000650  0.0  0.201613   0.0  0.234568  0.454493  0.672503  0.202848   
36   0.001024  0.0  0.201613   0.0  0.234568  0.436865  0.602472  0.204449   
323  0.003120  0.0  0.253666   0.0  0.222222  0.411381  0.735324  0.326592   
87   0.000733  0.0  0.147727   0.0  0.131687  0.490515  0.555098  0.238067   
318  0.004448  0.0  0.346041   0.0  0.327160  0.540525  0.662204  0.218507   

          RAD       TAX   PTRATIO         B     LSTAT  target  
35   0.173913  0.175573  0.702128  1.000000  0.219371    18.9  
36   0.173913  0.175573  0.702128  0.951233  0.267108    20.0  
323  0.173913  0.190840  0.744681  0.985451  0.276214    18.5  
87   0.086957  0.114504  0.627660  0.995587  0.185155    22.2  
318  0.130435  0.223282  0.617021  0.995739  0.238135    23.1

In [41]:
kr.kneighbors( input_ )

kr.kneighbors( input_ )[1]

kr.kneighbors( input_ )[1][0]

kr.kneighbors( input_ )[1][0].tolist()

[35, 36, 323, 87, 318]