# bit.ly/2lsQni7 ( 소문자 L )
파일 -> .ipynb 다운로드 -> 실습폴더에 업로드 하여 사용

# 모의고사2

# Q1.  ex2 파일을 참고하여, boston데이터에서 x와 y를 선언하라

In [0]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston

In [0]:
boston = load_boston()

In [0]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [0]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [0]:
y = y.reshape( [ -1 , 1])

In [0]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [0]:
data = pd.DataFrame(data = x,
                   columns = boston.feature_names)

data.head()

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]

In [0]:
data.describe()

CRIM          ZN       INDUS  ...     PTRATIO           B       LSTAT
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean     3.613524   11.363636   11.136779  ...   18.455534  356.674032   12.653063
std      8.601545   23.322453    6.860353  ...    2.164946   91.294864    7.141062
min      0.006320    0.000000    0.460000  ...   12.600000    0.320000    1.730000
25%      0.082045    0.000000    5.190000  ...   17.400000  375.377500    6.950000
50%      0.256510    0.000000    9.690000  ...   19.050000  391.440000   11.360000
75%      3.677083   12.500000   18.100000  ...   20.200000  396.225000   16.955000
max     88.976200  100.000000   27.740000  ...   22.000000  396.900000   37.970000

[8 rows x 13 columns]

# Q2. 전처리를 하자!

1. Target은 그대로 둘 것.
2. Description을 보고..
    1. 카테고리여야 할 것 같은 것은 더미!
    2. 그렇지 않은 것은 Min-Max Scailing


In [0]:
data_origin = data.copy()

In [0]:
a = np.array( [1,2,3,4,5]   )
b = a[:3]

a, b

(array([1, 2, 3, 4, 5]), array([1, 2, 3]))

In [0]:
b[1] = 10

In [0]:
b

array([ 1, 10,  3])

In [0]:
a

array([ 1, 10,  3,  4,  5])

In [0]:
data.head(4)

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94

[4 rows x 13 columns]

In [0]:
cols = list(data)

In [0]:
cols.remove(    'CHAS')
# try except, catch

In [0]:
for each in cols :
    min_each = data[each].min()
    max_each = data[each].max()
    boonmo = max_each - min_each
    data[each] = (data[each]-min_each)/boonmo
    
data.describe()

CRIM          ZN       INDUS  ...     PTRATIO           B       LSTAT
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean     0.040544    0.113636    0.391378  ...    0.622929    0.898568    0.301409
std      0.096679    0.233225    0.251479  ...    0.230313    0.230205    0.197049
min      0.000000    0.000000    0.000000  ...    0.000000    0.000000    0.000000
25%      0.000851    0.000000    0.173387  ...    0.510638    0.945730    0.144040
50%      0.002812    0.000000    0.338343  ...    0.686170    0.986232    0.265728
75%      0.041258    0.125000    0.646628  ...    0.808511    0.998298    0.420116
max      1.000000    1.000000    1.000000  ...    1.000000    1.000000    1.000000

[8 rows x 13 columns]

In [0]:
data_origin.describe()

CRIM          ZN       INDUS  ...     PTRATIO           B       LSTAT
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean     3.613524   11.363636   11.136779  ...   18.455534  356.674032   12.653063
std      8.601545   23.322453    6.860353  ...    2.164946   91.294864    7.141062
min      0.006320    0.000000    0.460000  ...   12.600000    0.320000    1.730000
25%      0.082045    0.000000    5.190000  ...   17.400000  375.377500    6.950000
50%      0.256510    0.000000    9.690000  ...   19.050000  391.440000   11.360000
75%      3.677083   12.500000   18.100000  ...   20.200000  396.225000   16.955000
max     88.976200  100.000000   27.740000  ...   22.000000  396.900000   37.970000

[8 rows x 13 columns]

In [0]:
# x = data_origin.values
x = data.values

In [0]:
x.shape, y.shape

((506, 13), (506, 1))

In [0]:
type(x), type(y)

(numpy.ndarray, numpy.ndarray)

# Q3. 모델링을 하자!

* Linear Regression을 한다!

* KNN을 이용한 Regression 도 해본다!

In [0]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

In [0]:
lr = LinearRegression()
kr = KNeighborsRegressor(n_neighbors=5, weights='distance')

In [0]:
lr.fit(x, y)
kr.fit(x, y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='distance')

In [0]:
l_pred = lr.predict(x)
k_pred = kr.predict(x)

# Q4. 평가하자!
* MSE 혹은 RMSE를 구해보자!
* R^2 값을 구해보자! ( Scikit-learn 의 r2_score 참고!)

### 쉬운길

In [0]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [0]:
print("선형회귀의 rmse : {:.3f}".format(np.sqrt(mean_squared_error(y, l_pred))))
print("KNN회귀의 rmse : {:.3f}".format(np.sqrt(mean_squared_error(y, k_pred))))

선형회귀의 rmse : 4.679
KNN회귀의 rmse : 0.000


In [0]:
print("선형회귀의 rmse : {:.3f}".format(r2_score(y, l_pred)))
print("KNN회귀의 rmse : {:.3f}".format(r2_score(y, k_pred)))

선형회귀의 rmse : 0.741
KNN회귀의 rmse : 1.000


In [0]:
data_origin.describe()

CRIM          ZN       INDUS  ...           B       LSTAT      target
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean     3.613524   11.363636   11.136779  ...  356.674032   12.653063   22.532806
std      8.601545   23.322453    6.860353  ...   91.294864    7.141062    9.197104
min      0.006320    0.000000    0.460000  ...    0.320000    1.730000    5.000000
25%      0.082045    0.000000    5.190000  ...  375.377500    6.950000   17.025000
50%      0.256510    0.000000    9.690000  ...  391.440000   11.360000   21.200000
75%      3.677083   12.500000   18.100000  ...  396.225000   16.955000   25.000000
max     88.976200  100.000000   27.740000  ...  396.900000   37.970000   50.000000

[8 rows x 14 columns]

In [0]:
data_origin.head(5)

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  target
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98    24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14    21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03    34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94    33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33    36.2

[5 rows x 14 columns]

In [0]:
lr.coef_

array([[ -9.60975755,   4.64204584,   0.56083933,   2.68673382,
         -8.63457306,  19.88368651,   0.06721501, -16.22666104,
          7.03913802,  -6.46332721,  -8.95582398,   3.69282735,
        -19.01724361]])

In [0]:
lr.intercept_

array([26.62026758])

In [0]:
data['target'] = y

In [0]:
data.head()

CRIM    ZN     INDUS  CHAS  ...   PTRATIO         B     LSTAT  target
0  0.000000  0.18  0.067815   0.0  ...  0.287234  1.000000  0.089680    24.0
1  0.000236  0.00  0.242302   0.0  ...  0.553191  1.000000  0.204470    21.6
2  0.000236  0.00  0.242302   0.0  ...  0.553191  0.989737  0.063466    34.7
3  0.000293  0.00  0.063050   0.0  ...  0.648936  0.994276  0.033389    33.4
4  0.000705  0.00  0.063050   0.0  ...  0.648936  1.000000  0.099338    36.2

[5 rows x 14 columns]

In [0]:
x[0]

array([0.        , 0.18      , 0.06781525, 0.        , 0.31481481,
       0.57750527, 0.64160659, 0.26920314, 0.        , 0.20801527,
       0.28723404, 1.        , 0.08967991])

# KNN 중요 포인트!

## 아래 코드 반복 실행 해보자!

In [0]:
kr.kneighbors( input_ )

kr.kneighbors( input_ )[1]

kr.kneighbors( input_ )[1][0]

kr.kneighbors( input_ )[1][0].tolist()

[55, 348, 347, 56, 256]

In [0]:
import random as rd
idx = rd.randint(0, 100)
print("{}번 row와 가장 가까운 것을 보고 싶다!".format(idx))
input_ = x[idx].reshape([1,-1])
print(kr.kneighbors(input_))

# data_origin.iloc[kr.kneighbors( input_ )[1][0].tolist()    ]
data.iloc[kr.kneighbors( input_ )[1][0].tolist()    ]

40번 row와 가장 가까운 것을 보고 싶다!
(array([[0.        , 0.12142595, 0.19614352, 0.19621074, 0.19724429]]), array([[ 40,  39, 292, 291, 290]]))


CRIM    ZN     INDUS  CHAS  ...   PTRATIO         B     LSTAT  target
40   0.000307  0.75  0.091276   0.0  ...  0.606383  0.996772  0.006898    34.9
39   0.000240  0.75  0.091276   0.0  ...  0.606383  0.996798  0.071468    30.8
292  0.000335  0.80  0.164589   0.0  ...  0.702128  1.000000  0.081954    27.9
291  0.000815  0.80  0.164589   0.0  ...  0.702128  1.000000  0.050497    37.3
290  0.000323  0.80  0.164589   0.0  ...  0.702128  1.000000  0.044150    28.5

[5 rows x 14 columns]