# bit.ly/2lsQni7 ( 소문자 L )
파일 -> .ipynb 다운로드 -> 실습폴더에 업로드 하여 사용

# 모의고사2

# Q1.  ex2 파일을 참고하여, boston데이터에서 x와 y를 선언하라

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston

In [2]:
boston = load_boston()

In [3]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [4]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [5]:
y = y.reshape( [ -1 , 1])

In [6]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [7]:
data = pd.DataFrame(data = x,
                   columns = boston.feature_names)

data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [8]:
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

# Q2. 전처리를 하자!

1. Target은 그대로 둘 것.
2. Description을 보고..
    1. 카테고리여야 할 것 같은 것은 더미!
    2. 그렇지 않은 것은 Min-Max Scailing


In [9]:
data_origin = data.copy()

In [10]:
a = np.array( [1,2,3,4,5]   )
b = a[:3]

a, b

(array([1, 2, 3, 4, 5]), array([1, 2, 3]))

In [11]:
b[1] = 10

In [12]:
b

array([ 1, 10,  3])

In [13]:
a

array([ 1, 10,  3,  4,  5])

In [14]:
data.head(4)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94

In [15]:
cols = list(data)

In [16]:
cols.remove(    'CHAS')
# try except, catch

In [17]:
for each in cols :
    min_each = data[each].min()
    max_each = data[each].max()
    boonmo = max_each - min_each
    data[each] = (data[each]-min_each)/boonmo
    
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     0.040544    0.113636    0.391378    0.069170    0.349167    0.521869   
std      0.096679    0.233225    0.251479    0.253994    0.238431    0.134627   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000851    0.000000    0.173387    0.000000    0.131687    0.445392   
50%      0.002812    0.000000    0.338343    0.000000    0.314815    0.507281   
75%      0.041258    0.125000    0.646628    0.000000    0.491770    0.586798   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     0.676364    0.242381    0.371713    0.422208    0.622929    0.898568   
std      0.289896    0.191482    0.378576    0.321636    0.230313    0.230205   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.433831    0.088259    0.130435    0.175573    0.510638    0.945730   
50%      0.768280    0.188949    0.173913    0.272901    0.686170    0.986232   
75%      0.938980    0.369088    1.000000    0.914122    0.808511    0.998298   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

            LSTAT  
count  506.000000  
mean     0.301409  
std      0.197049  
min      0.000000  
25%      0.144040  
50%      0.265728  
75%      0.420116  
max      1.000000

In [18]:
x = data_origin.values

In [19]:
x.shape, y.shape

((506, 13), (506, 1))

In [20]:
type(x), type(y)

(numpy.ndarray, numpy.ndarray)

# Q3. 모델링을 하자!

* Linear Regression을 한다!

* KNN을 이용한 Regression 도 해본다!

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

In [22]:
lr = LinearRegression()
kr = KNeighborsRegressor()

In [23]:
lr.fit(x, y)
kr.fit(x, y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [24]:
l_pred = lr.predict(x)
k_pred = kr.predict(x)

In [25]:
print(l_pred)
print(k_pred)

[[30.00384338]
 [25.02556238]
 [30.56759672]
 [28.60703649]
 [27.94352423]
 [25.25628446]
 [23.00180827]
 [19.53598843]
 [11.52363685]
 [18.92026211]
 [18.99949651]
 [21.58679568]
 [20.90652153]
 [19.55290281]
 [19.28348205]
 [19.29748321]
 [20.52750979]
 [16.91140135]
 [16.17801106]
 [18.40613603]
 [12.52385753]
 [17.67103669]
 [15.83288129]
 [13.80628535]
 [15.67833832]
 [13.38668561]
 [15.46397655]
 [14.70847428]
 [19.54737285]
 [20.8764282 ]
 [11.45511759]
 [18.05923295]
 [ 8.81105736]
 [14.28275814]
 [13.70675891]
 [23.81463526]
 [22.34193708]
 [23.10891142]
 [22.91502612]
 [31.35762569]
 [34.21510225]
 [28.02056414]
 [25.20386628]
 [24.60979273]
 [22.94149176]
 [22.09669817]
 [20.42320032]
 [18.03655088]
 [ 9.10655377]
 [17.20607751]
 [21.28152535]
 [23.97222285]
 [27.6558508 ]
 [24.04901809]
 [15.3618477 ]
 [31.15264947]
 [24.85686978]
 [33.10919806]
 [21.77537987]
 [21.08493555]
 [17.8725804 ]
 [18.51110208]
 [23.98742856]
 [22.55408869]
 [23.37308644]
 [30.36148358]
 [25.53056

# Q4. 평가하자!
* MSE 혹은 RMSE를 구해보자!
* R^2 값을 구해보자! ( Scikit-learn 의 r2_score 참고!)

### 쉬운길

In [26]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [27]:
print("선형회귀의 rmse : {:.3f}".format(np.sqrt(mean_squared_error(y, l_pred))))
print("KNN회귀의 rmse : {:.3f}".format(np.sqrt(mean_squared_error(y, k_pred))))

선형회귀의 rmse : 4.679
KNN회귀의 rmse : 4.896


In [28]:
print("선형회귀의 rmse : {:.3f}".format(r2_score(y, l_pred)))
print("KNN회귀의 rmse : {:.3f}".format(r2_score(y, k_pred)))

선형회귀의 rmse : 0.741
KNN회귀의 rmse : 0.716


In [29]:
data_origin.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [30]:
data_origin.head(10)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421   78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185   61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147   54.2  6.0622  3.0  222.0   
5  0.02985   0.0   2.18   0.0  0.458  6.430   58.7  6.0622  3.0  222.0   
6  0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
7  0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0   
8  0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
9  0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33  
5     18.7  394.12   5.21  
6     15.2  395.60  12.43  
7     15.2  396.90  19.15  
8     15.2  386.63  29.93  
9     15.2  386.71  17.10

In [31]:
lr.coef_

array([[-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,
         2.68673382e+00, -1.77666112e+01,  3.80986521e+00,
         6.92224640e-04, -1.47556685e+00,  3.06049479e-01,
        -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
        -5.24758378e-01]])

In [32]:
lr.intercept_

array([36.45948839])

In [33]:
data_origin['target'] = y

In [34]:
data_origin.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [35]:
kr.kneighbors( x[0:1])

(array([[ 0.        , 16.0970999 , 16.99995447, 18.40100218, 18.73017253]]),
 array([[  0, 241,  62,  81,  60]], dtype=int64))