# bit.ly/2lBGe2V (소문자 L)

## 인덱스 초기화도 포함해둠!

파일 -> .ipynb 다운로드 -> 구글드라이브에 업로드하여 사용

# 사후 실습 평가 I

# 데이터 로딩

In [0]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

In [0]:
db = load_diabetes()

논의를 쉽게 하기 위하여 다음과 같이 의미를 바꾸어 이해하기로 한다.

## Y는 당뇨병 진행율이라고 하자. 기본단위가 %이다.

사실 Y는, 인풋이 측정된 1년뒤의 당뇨병 진행상황에 대한 측정값이라고만 한다.

In [0]:
print(db.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - Age
      - Sex
      - Body mass index
      - Average blood pressure
      - S1
      - S2
      - S3
      - S4
      - S5
      - S6

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bra

In [0]:
db.data[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613])

In [0]:
####### 원본 데이터를 찾아서 가져왔음
####### 원본 데이터를 찾아서 가져왔음
temp = pd.read_csv('https://web.stanford.edu/~hastie/Papers/LARS/diabetes.data',sep = '\t')
temp.head()

AGE  SEX   BMI     BP   S1     S2    S3   S4      S5  S6    Y
0   59    2  32.1  101.0  157   93.2  38.0  4.0  4.8598  87  151
1   48    1  21.6   87.0  183  103.2  70.0  3.0  3.8918  69   75
2   72    2  30.5   93.0  156   93.6  41.0  4.0  4.6728  85  141
3   24    1  25.3   84.0  198  131.4  40.0  5.0  4.8903  89  206
4   50    1  23.0  101.0  192  125.4  52.0  4.0  4.2905  80  135

In [0]:
temp['SEX'] = temp['SEX']-1

In [0]:
temp.head()

AGE  SEX   BMI     BP   S1     S2    S3   S4      S5  S6    Y
0   59    1  32.1  101.0  157   93.2  38.0  4.0  4.8598  87  151
1   48    0  21.6   87.0  183  103.2  70.0  3.0  3.8918  69   75
2   72    1  30.5   93.0  156   93.6  41.0  4.0  4.6728  85  141
3   24    0  25.3   84.0  198  131.4  40.0  5.0  4.8903  89  206
4   50    0  23.0  101.0  192  125.4  52.0  4.0  4.2905  80  135

In [0]:
x = temp.drop(['Y'], axis = 1)
y = temp[['Y']]

In [0]:
x.shape, y.shape

((442, 10), (442, 1))

# Q1. 12번째 row의   S2컬럼의 값은 무엇인가?

In [0]:
# x[12:14]
# x.iloc[12, 5]
x.head(13)

AGE  SEX   BMI     BP   S1     S2    S3    S4      S5  S6
0    59    1  32.1  101.0  157   93.2  38.0  4.00  4.8598  87
1    48    0  21.6   87.0  183  103.2  70.0  3.00  3.8918  69
2    72    1  30.5   93.0  156   93.6  41.0  4.00  4.6728  85
3    24    0  25.3   84.0  198  131.4  40.0  5.00  4.8903  89
4    50    0  23.0  101.0  192  125.4  52.0  4.00  4.2905  80
5    23    0  22.6   89.0  139   64.8  61.0  2.00  4.1897  68
6    36    1  22.0   90.0  160   99.6  50.0  3.00  3.9512  82
7    66    1  26.2  114.0  255  185.0  56.0  4.55  4.2485  92
8    60    1  32.1   83.0  179  119.4  42.0  4.00  4.4773  94
9    29    0  30.0   85.0  180   93.4  43.0  4.00  5.3845  88
10   22    0  18.6   97.0  114   57.6  46.0  2.00  3.9512  83
11   56    1  28.0   85.0  184  144.8  32.0  6.00  3.5835  77
12   53    0  23.7   92.0  186  109.2  62.0  3.00  4.3041  81

In [0]:
print('s2 : ', x.loc[12,'S2'])
print('답은 109.2')

s2 :  109.2
답은 109.2


# Q2. min-max scailing 후, 12번째 row의 s2컬럼의 값은 무엇인가?

**조건**
1. S1~ S6 만 스케일링 할 것
1. 소수점 세자리까지, 그 미만 절삭.
2. 0번째 row부터 있습니다.

In [0]:
# x.head()
# x.columns
# list(x)
list(x)[-6:]

['S1', 'S2', 'S3', 'S4', 'S5', 'S6']

In [0]:
list(x)[-6:]

['S1', 'S2', 'S3', 'S4', 'S5', 'S6']

In [0]:
for col in list(x)[-6:] :
    min_x = x[col].min()
    max_x = x[col].max()
    boonmo = max_x - min_x
    x[col] = (x[col]-min_x)/boonmo
    
x.describe()

AGE         SEX         BMI  ...          S4          S5          S6
count  442.000000  442.000000  442.000000  ...  442.000000  442.000000  442.000000
mean    48.518100    0.468326   26.375792  ...    0.291996    0.485560    0.503942
std     13.109028    0.499561    4.418122  ...    0.182010    0.183366    0.174187
min     19.000000    0.000000   18.000000  ...    0.000000    0.000000    0.000000
25%     38.250000    0.000000   23.200000  ...    0.141044    0.357542    0.382576
50%     50.000000    0.000000   25.700000  ...    0.282087    0.478062    0.500000
75%     59.000000    1.000000   29.275000  ...    0.423131    0.610446    0.606061
max     79.000000    1.000000   42.200000  ...    1.000000    1.000000    1.000000

[8 rows x 10 columns]

In [0]:
print('s2 : ', x.loc[12,'S2'])
print('답은 0.336')

s2 :  0.33665338645418325
답은 0.336


# Linear Regression 모델링을 한 후 다음 질문들에 답하여라.

**조건**
1. train/valid/test 분리하지 않는다.
2. 모든 데이터를 이용한 예측값을 **y_pred**에 담는다.

In [0]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x,y)
y_pred = lr.predict(x)


# Q3. y_pred의 마지막 값은 무엇인가?
**조건**
1. 소수점 두번째 자리까지, 그 미만 절삭

In [0]:
# y_pred.tail()

In [0]:
# y_pred

In [0]:
y_pred[-1:]

array([[53.44727472]])

In [0]:
print(53.44)

53.44


# Q4. y와 y_pred를 이용하여 RMSE를 구하라.

**조건**
1. 소수점 두번째 자리 까지, 그 미만 절삭

In [0]:
y.shape,  y_pred.shape

((442, 1), (442, 1))

In [0]:
error = y - y_pred  #residual
squared_error = error**2
mean_squared_error = squared_error.mean()
root_mean_squared_error = np.sqrt(mean_squared_error)

In [0]:
np.sqrt(((y-y_pred)**2).mean())

Y    53.476129
dtype: float64

In [0]:
from sklearn.metrics import mean_squared_error

In [0]:
np.sqrt(mean_squared_error(y,y_pred))

53.47612876402657

In [0]:
print('답 : 53.47')

답 : 53.47


# 다음은 선형회귀모델에 대한 해석이다.
# 답에 % 표시는 하지 않도록 한다.

* e+00은 e+00을 무시하면 된다.
* e+01은 곱하기 10을 하여 생각하면 된다.
* e-02는 100을 나누어 생각하면 된다.

In [0]:
x.head()

AGE  SEX   BMI     BP  ...        S3        S4        S5        S6
0   59    1  32.1  101.0  ...  0.207792  0.282087  0.562217  0.439394
1   48    0  21.6   87.0  ...  0.623377  0.141044  0.222437  0.166667
2   72    1  30.5   93.0  ...  0.246753  0.282087  0.496578  0.409091
3   24    0  25.3   84.0  ...  0.233766  0.423131  0.572923  0.469697
4   50    0  23.0  101.0  ...  0.389610  0.282087  0.362385  0.333333

[5 rows x 10 columns]

In [0]:
lr.coef_

array([[-3.63612242e-02, -2.28596481e+01,  5.60296209e+00,
         1.11680799e+00, -2.22359252e+02,  1.49887251e+02,
         2.86443631e+01,  4.63248684e+01,  1.95101575e+02,
         1.84877213e+01]])

In [0]:
lr.intercept_

array([-171.48066963])

# Q5. 기본 진행율은 몇% 인가

**조건**
1. **음수라면 -도 적을것**
1. **소수점 절삭**
2. 그 숫자가 타당한지는 생각하지 않는다.

In [0]:
print('-171%')

-171%


# Q6. 혈압은 당뇨진행율에 어떤 영향을 주는가?

In [0]:
print('혈압이 커질수록 당뇨진행율 커진다')

혈압이 커질수록 당뇨진행율 커진다


In [0]:
x.describe()

AGE         SEX         BMI  ...          S4          S5          S6
count  442.000000  442.000000  442.000000  ...  442.000000  442.000000  442.000000
mean    48.518100    0.468326   26.375792  ...    0.291996    0.485560    0.503942
std     13.109028    0.499561    4.418122  ...    0.182010    0.183366    0.174187
min     19.000000    0.000000   18.000000  ...    0.000000    0.000000    0.000000
25%     38.250000    0.000000   23.200000  ...    0.141044    0.357542    0.382576
50%     50.000000    0.000000   25.700000  ...    0.282087    0.478062    0.500000
75%     59.000000    1.000000   29.275000  ...    0.423131    0.610446    0.606061
max     79.000000    1.000000   42.200000  ...    1.000000    1.000000    1.000000

[8 rows x 10 columns]

In [0]:
# 1.11680799e+00*(133-62)

1.11680799e+00*13

14.518503870000002

# Q7. BMI가 1늘어나면 당뇨 진행율은 몇퍼센트 늘어나는가?

**소수점 절삭**

In [0]:
print('5%')

5%


# Q8. S1은 당뇨진행율에 어떤 영향을 주는가?

In [0]:
print('S1이 커지면 당뇨 진행율을 낮춘다')

S1이 커지면 당뇨 진행율을 낮춘다


# Q9. S2가 0.1 커지면 당뇨 진행율은 몇퍼센트 커지는가?

**계산후 소수점 절삭하여 표기**

**소수점 절삭하여 계산하면 안됨**

In [0]:
1.49887251e+02 * 0.1

14.9887251

In [0]:
print('14%')

14%


# Q10. 나이가 30살 늘어나면 당뇨 진행율은 몇 % 변화가 생기는가?

**계산 후 소수점 절삭**

**소수점 절삭 후 계산하면 안됨**

**숫자만 적을 것**

**+,- 부호 표시 하지 말 것**

In [0]:
30*-3.63612242e-02

-1.090836726

In [0]:
print('1% 변화가 일어난다.')

1% 변화가 일어난다.


# KNN more! + data split!

In [0]:
from sklearn.model_selection import train_test_split as split

In [0]:
X_train, X_test, y_train, y_test = split(x, y, shuffle = True,
                                         test_size=0.33, random_state=42)

X_train.shape,  X_test.shape

((296, 10), (146, 10))

In [0]:
# X_train, X_valid, y_train, y_valid = split(X_train, y_train, test_size =0.2)

# X_train.shape, y_train.shape

In [0]:
X_train.reset_index(drop = True, inplace=True)
X_test.reset_index(drop = True, inplace=True)
y_train.reset_index(drop = True, inplace=True)
y_test.reset_index(drop = True, inplace=True)

In [0]:
from sklearn.neighbors import KNeighborsRegressor

In [0]:
knn = KNeighborsRegressor(n_neighbors=5, weights = 'distance',
                         metric = 'cosine')

In [0]:
knn.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='cosine',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='distance')

In [0]:
X_train.iloc[0]

AGE     51.000000
SEX      0.000000
BMI     23.500000
BP     101.000000
S1       0.480392
S2       0.395418
S3       0.376623
S4       0.282087
S5       0.521886
S6       0.545455
Name: 0, dtype: float64

In [0]:
knn.kneighbors(X_test.iloc[0:1]   )[0]

array([[5.96683311e-05, 8.79539982e-05, 1.22897932e-04, 1.63311523e-04,
        1.85076597e-04]])

In [0]:
knn.kneighbors(X_test.iloc[0:1]   )[1][0].tolist()

[158, 85, 224, 286, 197]

In [0]:
X_test.iloc[0:1]

AGE  SEX   BMI    BP  ...        S3        S4        S5        S6
0   61    0  25.8  90.0  ...  0.428571  0.423131  0.610446  0.484848

[1 rows x 10 columns]

In [0]:
X_train.iloc[knn.kneighbors(X_test.iloc[0:1]   )[1][0].tolist()]

AGE  SEX   BMI      BP  ...        S3        S4        S5        S6
158   60    0  25.6   87.00  ...  0.610390  0.141044  0.299344  0.393939
85    60    1  25.0   89.67  ...  0.311688  0.284908  0.439749  0.515152
224   55    1  23.4   83.00  ...  0.311688  0.282087  0.443575  0.575758
286   66    0  28.0  101.00  ...  0.233766  0.423131  0.562217  0.545455
197   61    0  24.0   91.00  ...  0.649351  0.141044  0.362385  0.227273

[5 rows x 10 columns]

In [0]:
 y_test.iloc[0:1]

Y
0  219

In [0]:
y_train.iloc[knn.kneighbors(X_test.iloc[0:1]   )[1][0].tolist()]

Y
158   81
85    97
224   53
286  173
197  118